services:
  alpaca-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18247:8000"
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_PAPER_TRADE=${ALPACA_PAPER_TRADE:-True}
      # OAuth Configuration for Pocket ID (server-side JWT validation only)
      - POCKET_ID_DOMAIN=${POCKET_ID_DOMAIN}
      - POCKET_ID_CLIENT_ID=${POCKET_ID_CLIENT_ID}
    restart: unless-stopped
    command: ["uv", "run", "python", "alpaca_mcp_server.py", "--transport", "http", "--host", "0.0.0.0", "--port", "8000"]